server:
  port: 8080
 
spring:
  application:
    name: pc-plataforma-comunicacao
  jpa:
    database: MYSQL
    show-sql: true
#    hibernate:
#      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/rf-plataforma-comunicacao?createDatabaseIfNotExist=true&useSSL=false
    username: renanfretta
    password: Ren@nFretta1986
  jackson:
    time-zone: America/Sao_Paulo
    locale: pt_BR